### ISSUE TITLE
Tried making a custom environment, the episode is not terminating

### ISSUE THREAD

**Issue by kharyal** [JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl#135]
I tried making an OpenAI gym's frozen lake like environment (code attached):
[frozenlake.zip](https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/files/6257540/frozenlake.zip)

The episodes are able to terminate when I run:
```
RLBase.test_runnable!(Env)
```

but not when I run:
```
run(RandomPolicy(action_space(Env)), Env, StopAfterEpisode(1)) 
```
What could be the reason for this?

**Comment by findmyway** [comment]
Hi @kharyal ,

Could you also paste the error you got? It's hard to diagnose without error trace.

**Comment by kharyal** [comment]
Hello!,
I did not get an error. The code keeps on running forever (the episode doesn't terminate).

Regards,
Chaitanya

**Comment by findmyway** [comment]
You seem to forget to reset the `is_termianted` info in `RLBase.reset!`:
```
	env.is_terminated = false
```

**Comment by kharyal** [comment]
Yes, strangely enough, this is working.

Even if `is_terminated` was always true, the code should have terminated, right?
