### ISSUE TITLE
Should `seed!` be part of the interface?

### ISSUE THREAD

**Issue by zsunberg** [JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl#24]
Should `seed!` be part of this interface to allow for easily reproducing exact trajectories? Or is there another standard way of seeding the environment's rng?

**Comment by findmyway** [comment]
Yes, `seed!` definitely should be part of this interface.  For now, only the constructor of the `AtariEnv` has a parameter named [`seed`](https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/blob/master/src/environments/atari.jl#L49) to initialize its internal rng.

I'll make a PR to update all the existing environments with `seed!` later.

**Comment by findmyway** [comment]
The `seed!` interface is now added in [ReinforcementLearningBase.jl](https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/blob/master/src/interface.jl#L261).

Also, environments now usually accept a keyword argument named `seed` for initialization.

**Comment by zsunberg** [comment]
Cool, this is good!
