### ISSUE TITLE
Issue while using Float32 as type for the MountainCar env

### ISSUE THREAD

**Issue by felixchalumeau** [JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl#62]
I am trying to use Float32 as type for the MountainCarEnv (basically stating that argument T = Float32) and I am having an issue. 

It's seems that CartPoleEnv, which is very similar to MountainCarEnv, works perfectly with different types. Thus this might come from the differences in the definition of both environments: 

MountainCarEnv: https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/blob/master/src/environments/classic_control/mountain_car.jl#L67

CartPoleEnv: https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/blob/master/src/environments/classic_control/cartpole.jl#L51

In CartPole, the parameters are directly converted to the chosen type but I can't find a line doing the same in MountainCarEnv.

Am I the only one to get this ? Hope that the suggestion can help fix this issue !

**Comment by findmyway** [comment]
> Am I the only one to get this ?

Yes, I think so. 👍 

It should be fixed now.

**Comment by felixchalumeau** [comment]
> Yes, I think so. 👍
> 
> It should be fixed now.

Do you mean that I wasn't the only one ;) ? 
In any case, thank you for fixing this !
