### ISSUE TITLE
Error while training a basic DQN in MountainCarEnv

### ISSUE THREAD

**Issue by felixchalumeau** [JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl#67]
Hi, 

I am experiencing an error while trying to train a basic DQN on MountainCarEnv with a CircularArrayBuffer. It seems that some functions are not found by julia: update!(cb::CircularArrayBuffer{T,N}, data::AbstractArray), _buffer_frame(cb::CircularArrayBuffer, I::Vector{Int}) and function _buffer_frame(cb::CircularArrayBuffer, i::Int).

I managed to run my code by manually adding those functions to my julia file. Getting them from ReinforcementLearningCore.jl/src/utils/base.jl :

```
@inline function _buffer_frame(cb::CircularArrayBuffer, i::Int)
    n = capacity(cb)
    idx = cb.first + i - 1
    if idx > n
        idx - n
    else
        idx
    end
end

_buffer_frame(cb::CircularArrayBuffer, I::Vector{Int}) = map(i -> _buffer_frame(cb, i), I)

function RL.update!(cb::CircularArrayBuffer{T,N}, data::AbstractArray) where {T,N}
    select_last_dim(cb.buffer, _buffer_frame(cb, cb.length)) .= data
    cb
end
```

The strange stuff is that I do not experience this issue when I run the absolute same code using the CartPoleEnv. 

I am having trouble understanding what is happening and I hope this will help pointing out something to improve in the source code.

**Comment by findmyway** [comment]
Could you provide your code to reproduce the error?

**Comment by felixchalumeau** [comment]
Just spent the last hour trying to reproduce it with no result. This is rather a good news even if I am absolutely not able to explain how this bug was fixed. 

In any case, sorry for this unnecessary issue.

**Comment by findmyway** [comment]
That sounds good. 😄 

By the way, it would be great if you can submit a PR to add your experiment with `MountainCarEnv` in RLZoo. Just like the one with `CartPoleEnv` [here](https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/master/src/experiments/rl_envs.jl#L12-L90).

**Comment by felixchalumeau** [comment]
> By the way, it would be great if you can submit a PR to add your experiment with `MountainCarEnv` in RLZoo. Just like the one with `CartPoleEnv` [here](https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/master/src/experiments/rl_envs.jl#L12-L90).

For sure ! I have a presentation to prepare today so it might be short but I will work on it next week !
