### ISSUE TITLE
Support CommonRLInterface

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl#70]
Though all the environments are written based on ReinforcementLearningBase.jl, it's relatively easy to support the minimal interfaces provided in CommonRLInterface.

```
struct CommonEnvWrapper{T<:RLBase.AbstractEnv} <: CommonRL.AbstractCommonEnv
     env::T
end

convert(CommonRL.AbstractCommonEnv, env::RLBase.AbstractEnv) = CommonEnvWrapper(env)

function CommonRL.step!(env::CommonEnvWrapper, action)
    env.env(action)
    obs = RLBase.observe(env.env)
    RLBase.get_state(obs), RLBase.get_reward(obs), RLBase.get_terminal(obs), obs
end

function CommonRL.reset!(env::CommonEnvWrapper)
    RLBase.reset!(env.env)
    obs = RLBase.observe(env.env)
    RLBase.get_state(obs), RLBase.get_reward(obs), RLBase.get_terminal(obs), obs
end

CommonRL.actions(env::CommonEnvWrapper) = RLBase.get_action_space(env)
```

What do you think? @zsunberg

**Comment by zsunberg** [comment]
Yep, this is what I had in mind! except there should also be a `convert(::Type{<:RLBase.AbstractEnv}, env::CommonRLInterface.CommonEnv)`

**Comment by findmyway** [comment]
I'll clean up APIs in RLBase a little and then work on this issue together with https://github.com/JuliaReinforcementLearning/CommonRLInterface.jl/issues/18#issuecomment-647871824 in the next week.

**Comment by findmyway** [comment]
Supported in RLBase directly. https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/pull/58
