### ISSUE TITLE
what happened to `render` function?

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl#79]
I see the api has changed.

**Comment by xiaodaigh** [comment]
Now just called `display(env)`

**Comment by findmyway** [comment]
Yep, you may also interested in discussions here: https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/pull/76#commitcomment-41085879
