### ISSUE TITLE
Implement Acrobot

### ISSUE THREAD

**Issue by jbrea** [JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl#9]
See [gym implementation](https://github.com/openai/gym/blob/master/gym/envs/classic_control/acrobot.py) and how we typically implement these classic examples [here](https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/blob/master/src/environments/classic_control/mountain_car.jl).

**Comment by gpavanb1** [comment]
Should we integrate this with [DifferentialEquations.jl](https://github.com/SciML/DifferentialEquations.jl) as the step in Acrobot involves integrating up to dt.

**Comment by jbrea** [comment]
Yes, but I guess it would be sufficient to rely on [OrdinaryDiffEq](https://github.com/SciML/OrdinaryDiffEq.jl) instead of the full DifferentialEquations package.
