### ISSUE TITLE
Port unmerged environments from FluxML/Gym.jl#37 to this package

### ISSUE THREAD

**Issue by RajGhugare19** [JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl#92]
This pr adds 1)Algorithmic 2)Atari 3) Toy-text envs . I think the Atari part is already ported here (https://github.com/JuliaReinforcementLearning/ArcadeLearningEnvironment.jl). Maybe I should start with Toy-text envs, they seem to be simpler than the algorithmic ones. Correct me if I am wrong @findmyway . Thank you :)

**Comment by RajGhugare19** [comment]
Why does the reset!() function not return anything?In CartPoleEnv one needs to explicitly call get_state, get_terminal, get_reward. In Gym the step or reset functions directly return these quantities. Is there any reason behind this change?

**Comment by findmyway** [comment]
See discussions here: https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/68
