### ISSUE TITLE
Question about observation/states

### ISSUE THREAD

**Issue by lorrp1** [JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl#99]
Hello, 
im trying writing a simple env to detect up/down of an array using dataframe. 
it is extremely easy on python-gym but
but i have a question:
 i dont understand how to return the observation, i have seen the guide and the cartpole example but i cant figure it out
does "RLBase.get_state(env::AcrobotEnv) " equal to the observation returned in gym's step?

i have just noticed that in the readme there: GymEnv | PyCall.jl
but no example on how to use it. (Can I just use a gym wrapped environment here? Would it slow down performance?)

also i wonder why the action space is missing in this example: https://juliareinforcementlearning.org/blog/how_to_write_a_customized_environment/

EDIT: found in an example

RLBase.observe(env::MazeEnv) =
    (
        reward = Float64(env.position == env.goal),
        terminal = env.position == env.goal,
        state = (env.position[2] - 1) * env.NX + env.position[1],
    )
but i still dont understand how the state works and why the .observe isnt in any env

**Comment by findmyway** [comment]
Hi @lorrp1 ,

> i dont understand how to return the observation, i have seen the guide and the cartpole example but i cant figure it out
does "RLBase.get_state(env::AcrobotEnv) " equal to the observation returned in gym's step?

Yes.

> i have just noticed that in the readme there: GymEnv | PyCall.jl
but no example on how to use it. (Can I just use a gym wrapped environment here? Would it slow down performance?)

The test cases may be helpful to you:
https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/blob/master/test/environments.jl

But yes, it will slow down performance slightly. (It mainly depends on the environment you're going to use to weigh the overhead.)


> also i wonder why the action space is missing in this example:

The action space was deprecated some time ago. You can call `get_actions` instead.

> RLBase.observe(env::MazeEnv) =
(
reward = Float64(env.position == env.goal),
terminal = env.position == env.goal,
state = (env.position[2] - 1) * env.NX + env.position[1],
)
but i still dont understand how the state works and why the .observe isnt in any env

Where did you find the example? I remember that the `observe` function was already deprecated. 

To better understand the design decision here, you may be interested in the [discussions](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/68)

**Comment by lorrp1** [comment]
Hello, thanks i have now understood it.

im getting an error with BasicDQNLearner but not with random policy
```
BoundsError: attempt to access (1, -1)
  at index [8]
```

using (from an example):
(if use length(get_state(env)) i do get error even related to (ns,128) since it returns 60 instead of 15 (the array of the state is 15*4)
```
ns, na = env.window, 2 # length(get_state(env)), length(get_actions(env)) 
rng = MersenneTwister(123)
agent = Agent(
    policy = QBasedPolicy(
        learner = BasicDQNLearner(
            approximator = NeuralNetworkApproximator(
                model = Chain(
                    Dense(ns, 128, relu; initW = glorot_uniform(rng)),
                    Dense(128, 128, relu; initW = glorot_uniform(rng)),
                    Dense(128, na; initW = glorot_uniform(rng)),
                ) |> cpu,
                optimizer = ADAM(),
            ),
            γ = 0.97,
            batch_size = 32,
            min_replay_history = 100,
            loss_func = huber_loss,
            rng = rng,
        ),
        explorer = EpsilonGreedyExplorer(
            kind = :exp,
            ϵ_stable = 0.01,
            decay_steps = 500,
            rng = rng,
        ),
    ),
    trajectory = CircularCompactSARTSATrajectory(
        capacity = 1000,
        state_type = Array,
        state_size = (ns,),
        action_type=Any,
        action_size = (na,),
        reward_type=Float64,
        terminal_type=Bool,
    ),
)
```
but this works fine:
```
run(
    Agent(
        ;policy = RandomPolicy(env),
        trajectory = VectCompactSARTSATrajectory(
            state_type=Array,
            action_type=Any,
            reward_type=Float64,
            terminal_type=Bool,
        ),
    ),
    tradeEnv(),
    StopAfterEpisode(1_000),
    hook
)
```
 using:
```
function getState(env::tradeEnv0)
    r =  Array(hcat(env.data[(env.t+env.startOnDF -env.window + 1):(env.t+env.startOnDF), :], last(env.info, env.window)))
    @show (size(r))
    return r 
end
```
it get this before getting the error: 
size(r) = (15, 4)
so it should be `state_size = (15,), ` like i used,i  guess

**Comment by findmyway** [comment]
Yes, you're right here.

If your state is a `Matrix` of size `(15,4)`, then you need to make several changes to the definition of the `Agent`:

First, 

```julia
    trajectory = CircularCompactSARTSATrajectory(
        capacity = 1000,
        state_type = Array,
        state_size = (ns,),
        action_type=Any,
        action_size = (na,),
        reward_type=Float64,
        terminal_type=Bool,
    )
```

As you can see, you need to change the `state_size` of `(ns,)` to `(15,4)` here.

Also note that, you'd better use `Float32` here or you'll get some performance issue.

The second place is:

```julia
model = Chain(
                    Dense(ns, 128, relu; initW = glorot_uniform(rng)),
                    Dense(128, 128, relu; initW = glorot_uniform(rng)),
                    Dense(128, na; initW = glorot_uniform(rng)),
                ) |> cpu,
```

To handle a state of size `(15,4)`, you need to flatten it before feeding it to a `Dense` layer.
Something like:

```julia
model = Chain(
                     x -> reshape(x, :, size(x)[end]),
                    Dense(15*4, 128, relu; initW = glorot_uniform(rng)),
                    Dense(128, 128, relu; initW = glorot_uniform(rng)),
                    Dense(128, na; initW = glorot_uniform(rng)),
                ) |> cpu,
```

<hr>

Besides, there's a known bug not fixed yet.

https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/88#issue-723904507

**Comment by lorrp1** [comment]
im trying with reshape like you wrote, but i got the error of dimension mismatch
so i used `vec(array())` in the function getState
and set` statesize = (60,) ` (should be fine now)

im trying different configuration (action with symbol or -1,1

i noticed that without the vec so without flattening the array i got the error on the action even without -1 `BoundsError: attempt to access (:b, :s)`

also i needed to change
` state_type = Array,`
to
` state_type = Any,` or float32 otherwise i got 
```
MethodError: Cannot `convert` an object of type 
  Float64 to an object of type 
  Array
```

using `RLBase.get_actions(env::tradeEnv0) = (1, -1) `
with         
`action_type=Int64, action_size=2, #(15,4),`
its stuck at 
`MethodError: no method matching update!(::CircularArrayBuffer{Int64,2}, ::Int64)`


using: `RLBase.get_actions(env::tradeEnv0) = (:b, :s) `with:
```
        state_type = Float32,
        state_size = (60,),
        action_type=Symbol,
        #action_size=2, #(15,4),
        reward_type=Float32,
        terminal_type=Bool,
```
manage to get through the first episode:

```
env.t = 100
size(vec(r)) = (60,)
size(vec(r)) = (60,)
```
then got error 
`MethodError: no method matching CartesianIndex(::Symbol, ::Int64)`

but all same with` action_size=2`, does not get through the first step

while the random policy just works fine
is there another policy without these bugs you would suggest me to try? (tried with iqn gives the same error for the action)

**Comment by findmyway** [comment]
> then got error
MethodError: no method matching CartesianIndex(::Symbol, ::Int64)

Like I said above, this is a known bug I haven't got time to fix: https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/88#issue-723904507

And the main problem is https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/88#issuecomment-711122702

One workaround is to add a wrapper to your customized environment like this:

https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/blob/d82d0579eea4017271b912a9b693c11130f36319/test/base.jl#L11-L15

Another one is that, you can directly encode the return of `get_actions` to numbers starting from `[1, 2]`. And handle it manually in `env(action)`.

> im trying with reshape like you wrote, but i got the error of dimension mismatch

Not sure why it triggers error but the code I provide above is used here: 

https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/master/src/experiments/atari.jl#L73

> also i needed to change
state_type = Array,
to
state_type = Any, or float32 otherwise i got

Yes, sorry that the name of this argument is kind of misunderstand... A better name would be `state_element_type`. I created an issue here to track this problem. https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/issues/158

Thanks again for reporting these issues. Let me know if you still have some other problems.

**Comment by lorrp1** [comment]
using this:
`RLBase.get_actions(env::tradeEnv0) = ([1,2])`
its seems to be fine

thank you

**Comment by lorrp1** [comment]
@findmyway 
hello, sorry to bother you again, but, could you suggest a way to do hyperparameter optimization? 
i have seen there was an open issue but there no more new information regarding it.

**Comment by findmyway** [comment]
Hi @lorrp1 ,

I haven't spent much time on hyperparameter search yet. 
But I can share some basic ideas here.

1. Define the hyperparameter search space and methods (grid search/bayesian methods...).
1. Select samples from the above space based on some metrics.
1. `@spawn` `Experiment`s with the above samples and collect evaluation results.
1. Update the methods in step1 with the results and repeat above steps.

Xref： https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/28

**Comment by lorrp1** [comment]
Hello @findmyway 
sorry i have not understood what's the pkg you are talking about.
i have searched MLJ but i cant find reference to things like: `@span `

**Comment by findmyway** [comment]
https://github.com/baggepinnen/Hyperopt.jl

This one may be easier to use.

MJLTuning.jl is too tightly coupled with MLJModel.

**Comment by lorrp1** [comment]
@findmyway Hyperopt.jl downgrade my version of  JuliaReinforcementLearning.jl

there is no reference in the documentation of Trajectories like: CircularCompactSARTSATrajectory

**Comment by findmyway** [comment]
> Hyperopt.jl downgrade my version of JuliaReinforcementLearning.jl

It seems  that https://github.com/STOR-i/GaussianProcesses.jl/pull/172 needs to be merged first.

> there is no reference in the documentation of Trajectories like: CircularCompactSARTSATrajectory

Yeah...
Doc related issues will be my focus in the next release.
